export type HubLang = 'th' | 'en';

export const STRINGS = {
  th: {
    progress: ['ทริปของฉัน', 'เตรียมตัว', 'ข้อมูลส่วนตัว', 'ใบยินยอม'],
    langToggle: 'EN',
    next: 'ถัดไป',
    back: 'ย้อนกลับ',
    submit: 'ส่งใบยินยอม',
    step1: {
      title: 'ทริปของฉัน',
      meeting: 'จุดนัดพบ',
      returnLabel: 'เวลากลับ',
      guide: 'ช่างภาพ / ไกด์',
      seats: 'ที่นั่ง',
      payment: 'การชำระเงิน',
      balance: 'ยอดคงเหลือ',
      included: 'รวมในแพ็กเกจ',
      excluded: 'ไม่รวม',
      alert15: 'กฎสาย 15 นาที — รถออกตรงเวลา ไม่รอ ไม่คืนมัดจำ',
    },
    step2: {
      title: 'เตรียมตัว',
      checklistHint: 'แตะเพื่อติ๊กเมื่อเตรียมแล้ว',
      items: ['กล้อง / มือถือ', 'รองเท้าเดินสบาย', 'น้ำดื่ม', 'ยาประจำตัว', 'บัตรประชาชน / Passport'],
      safety: 'ความปลอดภัย',
      notifyHome: 'แจ้งคนที่บ้านแล้ว',
      emergencySaen: 'เบอร์ฉุกเฉินแสน: 0452 044 382',
      checkWeather: 'เช็กพยากรณ์อากาศก่อนออก',
    },
    step3: {
      title: 'ข้อมูลส่วนตัว',
      name: 'ชื่อ-นามสกุล',
      phone: 'เบอร์โทร',
      email: 'อีเมล',
      emergency: 'เบอร์ฉุกเฉิน',
      required: 'จำเป็น',
      visa: 'ประเภทวีซ่า',
      visaStudent: 'นักเรียน (Student)',
      visaOther: 'อื่นๆ / ไม่ต้องใช้วีซ่า',
      oshcWarn: '⚠️ ต้องมี OSHC ที่ยังไม่หมดอายุ — กรอกเลขกรมธรรม์',
      oshcMembership: 'เลขกรมธรรม์ OSHC',
      health: 'สุขภาพ / แพ้อาหาร',
      experience: 'ระดับการถ่ายภาพ',
      expBeginner: 'เริ่มต้น',
      expHobbyist: 'งานอดิเรก',
      expExperienced: 'มีประสบการณ์',
    },
    step4: {
      title: 'ใบยินยอม',
      signHint: 'เซ็นชื่อดิจิทัลด้านล่าง',
      signRequired: 'กรุณาเซ็นชื่อและติ๊กครบ 6 ข้อ',
      c1: 'ยอมรับนโยบายคืนเงิน — มัดจำไม่คืนเมื่อมาสายหรือไม่มา',
      c2: 'ยอมรับความเสี่ยงและข้อจำกัดความรับผิด (ACL)',
      c3: 'ยอมรับข้อจำกัด OSHC (สำหรับนักเรียนเท่านั้น)',
      c4: 'ข้อมูลถูกต้อง และอายุ 18 ปีขึ้นไป',
      c5: 'สิทธิ์ขับรถเช่า — เฉพาะช่างภาพเท่านั้น',
      c6: 'สิทธิ์ Portfolio — ช่างภาพใช้ภาพโปรโมตได้',
    },
    step5: {
      title: 'ลงทะเบียนสำเร็จ',
      ref: 'เลขที่การจอง',
      signed: 'ลงนามเมื่อ',
      ip: 'IP (บันทึกตรวจสอบ)',
      sms: 'SMS เตือน 24 ชม. ก่อนออกทริป',
      done: 'กลับหน้าทริป',
    },
    paymentPaid: 'ชำระมัดจำแล้ว',
    paymentPending: 'รอชำระ',
  },
  en: {
    progress: ['My Trip', 'Prepare', 'Personal Info', 'Waivers'],
    langToggle: 'ไทย',
    next: 'Next',
    back: 'Back',
    submit: 'Submit waivers',
    step1: {
      title: 'My trip',
      meeting: 'Meeting point',
      returnLabel: 'Return',
      guide: 'Photographer / Guide',
      seats: 'Seats',
      payment: 'Payment',
      balance: 'Balance due',
      included: 'Included',
      excluded: 'Not included',
      alert15: '15-minute rule — vehicle departs on time. No wait. No deposit refund.',
    },
    step2: {
      title: 'Get ready',
      checklistHint: 'Tap to check when packed',
      items: ['Camera / phone', 'Comfortable shoes', 'Water bottle', 'Personal medication', 'ID / Passport'],
      safety: 'Safety',
      notifyHome: 'I have notified someone at home',
      emergencySaen: 'Saen emergency line: 0452 044 382',
      checkWeather: 'I checked the weather forecast',
    },
    step3: {
      title: 'Personal details',
      name: 'Full name',
      phone: 'Mobile',
      email: 'Email',
      emergency: 'Emergency contact',
      required: 'Required',
      visa: 'Visa type',
      visaStudent: 'Student visa',
      visaOther: 'Other / Not required',
      oshcWarn: '⚠️ Valid OSHC required — enter membership number',
      oshcMembership: 'OSHC policy number',
      health: 'Health / allergies',
      experience: 'Photography experience',
      expBeginner: 'Beginner',
      expHobbyist: 'Hobbyist',
      expExperienced: 'Experienced',
    },
    step4: {
      title: 'Waivers & consent',
      signHint: 'Sign below with your finger or stylus',
      signRequired: 'Complete all 6 checkboxes and sign',
      c1: 'Refund policy — no deposit refund for late/no-show',
      c2: 'Risk & liability limitation (ACL binding)',
      c3: 'OSHC limitation (student travellers only)',
      c4: 'Information is accurate and I am 18+',
      c5: 'Rental driving — photographers only may drive',
      c6: 'Portfolio rights — photographer may use images for promotion',
    },
    step5: {
      title: 'Registration complete',
      ref: 'Booking reference',
      signed: 'Signed at',
      ip: 'IP (audit trail)',
      sms: 'SMS reminder 24hrs before trip',
      done: 'Back to trip hub',
    },
    paymentPaid: 'Deposit paid',
    paymentPending: 'Payment pending',
  },
} as const;
