import type { CustomerBookingRow } from './tripsSheetApi';

/** Portal / login fallback when GAS Customer_Bookings is unreachable. */
export const MOCK_CUSTOMER_BOOKINGS: CustomerBookingRow[] = [
  {
    bookingId: 'BK-001',
    customerName: 'Saen Test',
    tourCode: 'KIA-1DAY',
    tourName: 'The Coastal Cliffs',
    phone: '',
    pickupLocation: 'thaitown_main',
    pickupDisplay: 'Thai Town, Haymarket',
    tourDate: '2026-06-15',
    departTime: '08:00 AM',
    guests: 4,
    totalAmount: 1000,
    fbChatUrl: 'https://m.me/trip2talk',
    notes: 'Test booking - Kiama coastal trip',
  },
  {
    bookingId: 'BK-002',
    customerName: 'Nong Ploy',
    tourCode: 'CAN-2D1N',
    tourName: 'The Golden Fields',
    phone: '',
    pickupLocation: 'thaitown_main',
    pickupDisplay: 'Thai Town, Haymarket',
    tourDate: '2026-10-05',
    departTime: '07:00 AM',
    guests: 4,
    totalAmount: 1520,
    fbChatUrl: 'https://m.me/trip2talk',
    notes: 'Spring canola fields trip',
  },
  {
    bookingId: 'BK-003',
    customerName: 'Test Client NZ',
    tourCode: 'NZ-6D5N',
    tourName: 'The Alpine Kingdom',
    phone: '',
    pickupLocation: 'airport_terminal',
    pickupDisplay: 'Sydney Airport Terminal 1',
    tourDate: '2026-04-12',
    departTime: '06:00 AM',
    guests: 3,
    totalAmount: 6900,
    fbChatUrl: 'https://m.me/trip2talk',
    notes: 'New Zealand 6D5N overnight trip',
  },
];
